CC = aarch64-linux-gnu-gcc -march=armv8-a -mtune=cortex-a53 -L/home/faezeh/openssl -L/home/faezeh/csec-modex/proxies -static 
# Mkae the model smaller
# CFLAGS += -DVERBOSE 
LDLIBS += -lssl -lcrypto

P1 = server
P2 = client

P1_SRC = server.c net.c lib.c
P2_SRC = client.c net.c lib.c

